name: greeting-action
description: A GitHub action that you can create a greeting message for your new contributors.

branding:
  icon: 'thumbs-up'
  color: 'green'

inputs:
  message:
    description: 'Comment to post on an individual''s first pull request'

runs:
    name: Take an issue
    runs-on: ubuntu-latest
    steps:
    - name: take the issue
      uses: bdougie/take-action@main
